"""Gribbosaurus Rex API.

Endpoints
  GET /models/status   per-model: latest run, freshness, next expected cycle
  GET /runs            recent run history (the "new GRIB available" feed)
  GET /point           multi-model forecast time series at lat/lon
  GET /grid            blended wind field over the race area
  GET /obs             recent observations (yacht, METAR, buoys)
  GET /scores          latest confidence per model + current blend weights
  GET /scores/history  confidence time series (dashboard chart)
  POST /fetch          trigger one polling pass now (runs + obs + verify)

Set GRIBBO_WATCH=1 to run the background poller inside the API process;
the NMEA listener starts too when enabled in the race config.
"""

from __future__ import annotations

import os
from contextlib import asynccontextmanager
from datetime import datetime, timezone

from fastapi import FastAPI, HTTPException, Query, Request, Response

from gribbosaurus_rex.config import load_config
from gribbosaurus_rex.fetch.base import cycle_db
from gribbosaurus_rex.fetch.registry import get_fetcher
from gribbosaurus_rex.obs.store import ObsStore
from gribbosaurus_rex.scheduler import Poller, check_all, obs_and_verify_pass
from gribbosaurus_rex.store.runs import RunStore

cfg = load_config()
_poller: Poller | None = None
_nmea = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    global _poller, _nmea
    if os.environ.get("GRIBBO_WATCH") == "1":
        _poller = Poller(cfg)
        _poller.start()
    if cfg.obs.nmea.enabled:
        from gribbosaurus_rex.obs.nmea import NmeaListener

        _nmea = NmeaListener(cfg, ObsStore(cfg.db_path))
        _nmea.start()
    yield
    if _poller:
        _poller.stop()
    if _nmea:
        _nmea.stop()


app = FastAPI(title="Gribbosaurus Rex API", lifespan=lifespan)


@app.get("/models/status")
def models_status():
    store = RunStore(cfg.db_path)
    now = datetime.now(timezone.utc)
    out = []
    for model in cfg.models:
        fetcher = get_fetcher(model)
        latest = store.latest_complete(model)
        candidates = fetcher.candidate_cycles(now)
        newest_candidate = cycle_db(candidates[0]) if candidates else None
        age_h = None
        if latest:
            age_h = round((now - datetime.fromisoformat(latest.cycle))
                          .total_seconds() / 3600, 1)
        out.append({
            "model": model,
            "latest_cycle": latest.cycle if latest else None,
            "fetched_at": latest.finished_at if latest else None,
            "cycle_age_hours": age_h,
            "n_files": latest.n_files if latest else 0,
            "size_mb": round(latest.bytes / 1e6, 1) if latest else 0,
            "newest_possible_cycle": newest_candidate,
            "up_to_date": bool(latest and latest.cycle == newest_candidate),
        })
    return {"race": cfg.name, "time": now.isoformat(timespec="seconds"),
            "models": out}


@app.get("/runs")
def runs(model: str | None = None, limit: int = 40):
    store = RunStore(cfg.db_path)
    return [vars(r) for r in store.list_runs(model=model, limit=limit)]


@app.get("/point")
def point(lat: float = Query(...), lon: float = Query(...)):
    from gribbosaurus_rex.extract import latest_point_forecasts

    if not cfg.bbox.padded(1.0).contains(lat, lon):
        raise HTTPException(422, f"({lat},{lon}) is outside race area '{cfg.name}'")
    df = latest_point_forecasts(cfg, lat, lon)
    if df.empty:
        raise HTTPException(
            503, "No model runs on disk yet — POST /fetch or run fetch-once.")
    df["time"] = df["time"].astype(str)
    return df.to_dict(orient="records")


@app.get("/grid")
def grid(valid_time: str | None = None):
    from gribbosaurus_rex.pipeline import run as run_pipeline

    try:
        df = run_pipeline(cfg, valid_time=valid_time)
    except RuntimeError as e:
        raise HTTPException(503, str(e)) from e
    return df.to_dict(orient="records")


@app.get("/obs")
def obs(window_h: float = 24, source: str | None = None):
    store = ObsStore(cfg.db_path)
    return [vars(o) for o in store.recent_obs(window_h, source=source)]


@app.get("/scores")
def scores():
    from gribbosaurus_rex.pipeline import current_weights

    store = ObsStore(cfg.db_path)
    weights, source = current_weights(cfg)
    return {
        "race": cfg.name,
        "latest": store.latest_scores(),
        "blend_weights": weights,
        "weight_source": source,   # "confidence" once verification has data
    }


@app.get("/scores/history")
def scores_history(model: str | None = None, limit: int = 500):
    store = ObsStore(cfg.db_path)
    return [dict(r) for r in store.score_history(model=model, limit=limit)]


@app.get("/scores.json")
def scores_json(request: Request):
    """The Stingray artefact (contract schema 1.0): ETag/Last-Modified,
    honors If-None-Match. Regenerated by every arbiter/poller pass."""
    from email.utils import formatdate

    from gribbosaurus_rex.publish import etag_for, scores_path

    path = scores_path(cfg)
    if not path.exists():
        raise HTTPException(
            503, "scores.json not generated yet — run: "
                 "python -m gribbosaurus_rex arbiter-once")
    content = path.read_bytes()
    etag = etag_for(content)
    if request.headers.get("if-none-match") == etag:
        return Response(status_code=304, headers={"ETag": etag})
    return Response(
        content=content, media_type="application/json",
        headers={
            "ETag": etag,
            "Last-Modified": formatdate(path.stat().st_mtime, usegmt=True),
            "Cache-Control": "no-cache",
        })


@app.post("/fetch")
def fetch_now():
    store = RunStore(cfg.db_path)
    fetched = check_all(cfg, store)
    phase2 = obs_and_verify_pass(cfg, store)
    return {"fetched": fetched, **phase2}
